apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    version: 1
    editable: true
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus