# do not delete this file
global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets:
          - 'otelcol:8888'
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
